name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://static.cowtransfer.com/e30224a8-e217-4699-91fc-71db7e60ab4b/49e2c95e-6552-4a7f-96cb-b2f9a9602d7f/20200508/MIUI_V12_%E5%B0%8F%E7%B1%B3MAX3_nitrogen_20.5.7_10_%E5%BC%80%E5%8F%91%E7%89%88_57ebca1b_wx%E5%85%AC%E4%BC%97%E5%8F%B7_DROM%E5%88%B7%E6%9C%BA.zip?onett=3df223e060f3338bf5f9543ca2a2eae5&attname=MIUI_V12_%E5%B0%8F%E7%B1%B3MAX%203_nitrogen_20.5.7_10_%E5%BC%80%E5%8F%91%E7%89%88_57ebca1b_wx%E5%85%AC%E4%BC%97%E5%8F%B7_DROM%E5%88%B7%E6%9C%BA.zip
  ROM_NAME: MIUI for Android 10
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              mkdir final
              zip -r final/GSI.zip /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/
       
       - name: Upload GSI to BitSend
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer bit final/GSI.zip

         
            
